apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: shradha11/demo-image:{{ .Values.image_tag }}
        #image: ashutosh04/blogapp:<IMAGE_TAG>
        ports:
        - containerPort: 5000
        env:
            - name: FLASK_ENV
              value: "stage"